
server.port: 8092
spring:
    application.name: eventDrivenConfigServer
    cloud:
        config.server.git:
                        uri: https://github.com/tushar4891/EventDrivenConfiguration
                        username: 
                        password: 
                        clone-on-start: true
                        default-label: main 
        fail-fast: true
        

